
stages:
    - pull
    - build
    - push

before_script:
    - docker info


pull:
    stage: pull
    script:
        - 'docker pull csanchez/jenkins-swarm-slave || :'
        - 'docker pull debian:8.1 || :'
        - 'docker pull dock0/arch || :'
        - 'docker pull evarga/jenkins-slave || :'
        - 'docker pull java:8-jdk || :'
        - 'docker pull jenkins:2.7.4 || :'
        - 'docker pull phusion/baseimage:0.9.17 || :'
        - 'docker pull pitkley/jenkins-slave-texlive || :'
        - 'docker pull pitkley/jenkins-slave-texlive:swarm || :'
        - 'docker pull pitkley/jenkins-swarm-slave || :'
        - 'docker pull python:2.7 || :'

arch-makepkg:latest:build:
    stage: build
    script:
        - cd arch-makepkg
        - docker build -t pitkley/arch-makepkg:latest .

arch-makepkg:latest:push:
    stage: push
    script:
        - docker push pitkley/arch-makepkg:latest

jenkins-dood:2:build:
    stage: build
    script:
        - cd jenkins-dood/2
        - docker build -t pitkley/jenkins-dood:2 .

jenkins-dood:2:push:
    stage: push
    script:
        - docker push pitkley/jenkins-dood:2

jenkins-dood:2.7.4:build:
    stage: build
    script:
        - cd jenkins-dood/2.7.4
        - docker build -t pitkley/jenkins-dood:2.7.4 .

jenkins-dood:2.7.4:push:
    stage: push
    script:
        - docker push pitkley/jenkins-dood:2.7.4

jenkins-dood:latest:build:
    stage: build
    script:
        - cd jenkins-dood/latest
        - docker build -t pitkley/jenkins-dood:latest .

jenkins-dood:latest:push:
    stage: push
    script:
        - docker push pitkley/jenkins-dood:latest

jenkins-slave-texlive:latest:build:
    stage: build
    script:
        - cd jenkins-slave-texlive
        - docker build -t pitkley/jenkins-slave-texlive:latest .

jenkins-slave-texlive:latest:push:
    stage: push
    script:
        - docker push pitkley/jenkins-slave-texlive:latest

jenkins-slave-texlive:swarm:build:
    stage: build
    script:
        - cd jenkins-slave-texlive/swarm
        - docker build -t pitkley/jenkins-slave-texlive:swarm .

jenkins-slave-texlive:swarm:push:
    stage: push
    script:
        - docker push pitkley/jenkins-slave-texlive:swarm

jenkins-slave-texlive-personal:latest:build:
    stage: build
    script:
        - cd jenkins-slave-texlive-personal
        - docker build -t pitkley/jenkins-slave-texlive-personal:latest .

jenkins-slave-texlive-personal:latest:push:
    stage: push
    script:
        - docker push pitkley/jenkins-slave-texlive-personal:latest

jenkins-slave-texlive-personal:swarm:build:
    stage: build
    script:
        - cd jenkins-slave-texlive-personal/swarm
        - docker build -t pitkley/jenkins-slave-texlive-personal:swarm .

jenkins-slave-texlive-personal:swarm:push:
    stage: push
    script:
        - docker push pitkley/jenkins-slave-texlive-personal:swarm

jenkins-swarm-slave:latest:build:
    stage: build
    script:
        - cd jenkins-swarm-slave
        - docker build -t pitkley/jenkins-swarm-slave:latest .

jenkins-swarm-slave:latest:push:
    stage: push
    script:
        - docker push pitkley/jenkins-swarm-slave:latest

libpst:latest:build:
    stage: build
    script:
        - cd libpst
        - docker build -t pitkley/libpst:latest .

libpst:latest:push:
    stage: push
    script:
        - docker push pitkley/libpst:latest

maven-swarm:3:build:
    stage: build
    script:
        - cd maven-swarm/3
        - docker build -t pitkley/maven-swarm:3 .

maven-swarm:3:push:
    stage: push
    script:
        - docker push pitkley/maven-swarm:3

maven-swarm:3.3:build:
    stage: build
    script:
        - cd maven-swarm/3.3
        - docker build -t pitkley/maven-swarm:3.3 .

maven-swarm:3.3:push:
    stage: push
    script:
        - docker push pitkley/maven-swarm:3.3

maven-swarm:3.3.9:build:
    stage: build
    script:
        - cd maven-swarm/3.3.9
        - docker build -t pitkley/maven-swarm:3.3.9 .

maven-swarm:3.3.9:push:
    stage: push
    script:
        - docker push pitkley/maven-swarm:3.3.9

maven-swarm:latest:build:
    stage: build
    script:
        - cd maven-swarm/latest
        - docker build -t pitkley/maven-swarm:latest .

maven-swarm:latest:push:
    stage: push
    script:
        - docker push pitkley/maven-swarm:latest

platformio:2:build:
    stage: build
    script:
        - cd platformio/2
        - docker build -t pitkley/platformio:2 .

platformio:2:push:
    stage: push
    script:
        - docker push pitkley/platformio:2

platformio:2.11.2:build:
    stage: build
    script:
        - cd platformio/2.11.2
        - docker build -t pitkley/platformio:2.11.2 .

platformio:2.11.2:push:
    stage: push
    script:
        - docker push pitkley/platformio:2.11.2

platformio:3:build:
    stage: build
    script:
        - cd platformio/3
        - docker build -t pitkley/platformio:3 .

platformio:3:push:
    stage: push
    script:
        - docker push pitkley/platformio:3

platformio:3.0.1:build:
    stage: build
    script:
        - cd platformio/3.0.1
        - docker build -t pitkley/platformio:3.0.1 .

platformio:3.0.1:push:
    stage: push
    script:
        - docker push pitkley/platformio:3.0.1

platformio:latest:build:
    stage: build
    script:
        - cd platformio/latest
        - docker build -t pitkley/platformio:latest .

platformio:latest:push:
    stage: push
    script:
        - docker push pitkley/platformio:latest

python-swarm:2:build:
    stage: build
    script:
        - cd python-swarm/2
        - docker build -t pitkley/python-swarm:2 .

python-swarm:2:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:2

python-swarm:2.6:build:
    stage: build
    script:
        - cd python-swarm/2.6
        - docker build -t pitkley/python-swarm:2.6 .

python-swarm:2.6:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:2.6

python-swarm:2.6.9:build:
    stage: build
    script:
        - cd python-swarm/2.6.9
        - docker build -t pitkley/python-swarm:2.6.9 .

python-swarm:2.6.9:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:2.6.9

python-swarm:2.7:build:
    stage: build
    script:
        - cd python-swarm/2.7
        - docker build -t pitkley/python-swarm:2.7 .

python-swarm:2.7:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:2.7

python-swarm:2.7.12:build:
    stage: build
    script:
        - cd python-swarm/2.7.12
        - docker build -t pitkley/python-swarm:2.7.12 .

python-swarm:2.7.12:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:2.7.12

python-swarm:3:build:
    stage: build
    script:
        - cd python-swarm/3
        - docker build -t pitkley/python-swarm:3 .

python-swarm:3:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:3

python-swarm:3.4:build:
    stage: build
    script:
        - cd python-swarm/3.4
        - docker build -t pitkley/python-swarm:3.4 .

python-swarm:3.4:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:3.4

python-swarm:3.4.5:build:
    stage: build
    script:
        - cd python-swarm/3.4.5
        - docker build -t pitkley/python-swarm:3.4.5 .

python-swarm:3.4.5:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:3.4.5

python-swarm:3.5:build:
    stage: build
    script:
        - cd python-swarm/3.5
        - docker build -t pitkley/python-swarm:3.5 .

python-swarm:3.5:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:3.5

python-swarm:3.5.2:build:
    stage: build
    script:
        - cd python-swarm/3.5.2
        - docker build -t pitkley/python-swarm:3.5.2 .

python-swarm:3.5.2:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:3.5.2

python-swarm:latest:build:
    stage: build
    script:
        - cd python-swarm/latest
        - docker build -t pitkley/python-swarm:latest .

python-swarm:latest:push:
    stage: push
    script:
        - docker push pitkley/python-swarm:latest

samba-ad-dc:latest:build:
    stage: build
    script:
        - cd samba-ad-dc
        - docker build -t pitkley/samba-ad-dc:latest .

samba-ad-dc:latest:push:
    stage: push
    script:
        - docker push pitkley/samba-ad-dc:latest


